apiVersion: core.eda.nokia.com/v1
kind: NodeProfile
metadata:
  name: topology-srlinux-25.10.3
  namespace: clab-topology
spec:
  annotate: true
  images:
    - image: fake.bin
      imageMd5: fake.bin.md5
  llmDb: >-
    https://eda-asvr.eda-system.svc/eda-system/llm-dbs/llm-db-srlinux-ghcr-25.10.3/llm-embeddings-srl-25-10-3.tar.gz
  nodeUser: admin
  onboardingPassword: NokiaSrl1!
  onboardingUsername: admin
  operatingSystem: srl
  port: 57410
  version: 25.10.3
  versionMatch: v25\.10\.3.*
  versionPath: .system.information.version
  yang: >-
    https://eda-asvr.eda-system.svc/eda-system/clab-schemaprofiles/clab-srlinux-25.10.3/srlinux-25.10.3.zip
