apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: leaf3-ethernet-1-1
  namespace: clab-topology
spec:
  description: interSwitch link to leaf1
  enabled: true
  encapType: 'Null'
  ethernet:
    speed: 100G
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-1
      lacpPortPriority: 32768
      node: leaf3
  mtu: 9000
  type: Interface
